
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Jenni Thomsen | Counseling in Omaha
subtitle: "My goal as a therapist is to provide a safe and compassionate place where counseling clients from all over Omaha can get encouragement and support as they navigate through the challenges of life."
url: "https://jennirennecounseling.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/img/logo.png"

description: My goal as a therapist is to provide a safe and compassionate place where counseling clients from all over Omaha can get encouragement and support as they navigate through the challenges of life.
social:
  name: Jenni Thomsen

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

plugins:
  - jekyll-seo-tag
